# Generated by Django 6.0.3 on 2026-03-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('profesor', 'Profesor'), ('bibliotecario', 'Bibliotecario'), ('admin', 'Administrador')], default='estudiante', max_length=20),
        ),
    ]
