# Generated by Django 6.0.3 on 2026-03-20 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_libro', models.CharField(max_length=50, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=150)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('anio_publicacion', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('prestado', 'Prestado')], default='disponible', max_length=20)),
                ('portada_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'libros',
            },
        ),
        migrations.CreateModel(
            name='EjemplarLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_inventario', models.CharField(max_length=80, unique=True)),
                ('condicion', models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular')], default='bueno', max_length=20)),
                ('disponibilidad', models.CharField(choices=[('disponible', 'Disponible'), ('prestado', 'Prestado'), ('mantenimiento', 'Mantenimiento')], default='disponible', max_length=20)),
                ('libro', models.ForeignKey(db_column='id_libro', on_delete=django.db.models.deletion.CASCADE, related_name='ejemplares', to='biblioteca.libro')),
            ],
            options={
                'db_table': 'ejemplares_libro',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('devuelto', 'Devuelto')], default='activo', max_length=20)),
                ('ejemplar', models.ForeignKey(db_column='id_ejemplar', on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='biblioteca.ejemplarlibro')),
                ('libro', models.ForeignKey(db_column='id_libro', on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='biblioteca.libro')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prestamos',
            },
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devolucion', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('prestamo', models.OneToOneField(db_column='id_prestamo', on_delete=django.db.models.deletion.CASCADE, related_name='devolucion', to='biblioteca.prestamo')),
            ],
            options={
                'db_table': 'devoluciones',
            },
        ),
        migrations.CreateModel(
            name='SolicitudPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('libro', models.ForeignKey(db_column='id_libro', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='biblioteca.libro')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'solicitudes_prestamo',
            },
        ),
    ]
